### ISSUE TITLE
How do I run this?

### ISSUE THREAD

**Issue by TomClarkson** [Dean177/jumpy-bird-react-demo#2]

**Comment by Dean177** [comment]
'gulp compile-server', then in a separate terminal 'gulp app-server'. EDIT: updated the readme now.

**Comment by TomClarkson** [comment]
I got the app run by replacing your branch of react-highlight with the npm version

I see the is a link to http://alpaca:9090/ why is that?

**Comment by Dean177** [comment]
Alpaca is the hostname of my Laptop, this was used as part of a talk, and its easier to remember than some IP address.
react-hight had some issue when i was using this, PR to switch back to the NPM one?
